---
galaxy_info:
  author: rflocfloc
  description: Role to pull dotfiles and stow them.

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.10
  galaxy_tags:
    - dotfiles
    - stow
    - github

dependencies: []
