---
- hosts: localhost
  connection: local
  gather_facts: true

  ### VARS
  # vars of imported tasks
  vars:
    nerdfonts_setup: true
    nerdfonts_path: "/usr/local/share/fonts"
    nerdfonts_to_install:
      - NerdFontsSymbolsOnly
      - FiraCode
      - Overpass
      - JetBrainsMono
    conda_setup: true
    conda_url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-{{ ansible_architecture }}.sh"
    conda_path: "~/conda"


  ### PRE TASKS
  pre_tasks:
    - name: Update package cache
      tags: [ always ]
      become: true
      ansible.builtin.package: update_cache=yes
      changed_when: false


  ### TASKS
  tasks:
    - name: System bootstrap (repos and updates)
      tags: [ repos ]
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - "tasks/repos_{{ ansible_distribution }}.yml"
        - "tasks/repos_{{ ansible_os_family }}.yml"

    - ansible.builtin.import_tasks: "tasks/flatpak.yml"
      tags: [ flatpak, repos ]

    # - name: Load distribution-specific cli_utils variables
    #   tags: [ cli ]
    #   include_vars: "{{ item }}"
    #   with_first_found:
    #     - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    #     - "vars/{{ ansible_distribution }}.yml"
    #     - "vars/{{ ansible_os_family }}.yml"
    #     - "vars/default.yml"
    #
    # - ansible.builtin.import_tasks: "tasks/cli.yml"
    #   tags: [ cli ]
    #
    - name: Setup git role
      ansible.builtin.import_role:
        name: git
      tags: [ git, vcs ]
      vars:
        git_manage_config: true
        git_user_name: "rflocfloc"
        git_user_email: "riccardoscandino@gmail.com"
        git_manage_project_dirs: true
        git_project_dirs:
          - "~/Projects"
          - "~/Projects/Personal"
          - "~/Projects/Work"

    - name: Setup conda role
      ansible.builtin.import_tasks: "tasks/conda.yml"
      tags: [ conda, dev ]
      when: conda_setup | bool

    - name: Manage dotfiles role
      ansible.builtin.import_role:
        name: dotfiles
      tags: [ dotfiles ]
      vars:
        dotfiles_github_repo: "git@github.com-personal:rflocfloc/dotfiles.git"
        dotfiles_github_ssh_key: "~/.ssh/id_ed25519_github.pub"
        dotfiles_delete_bashrc: true
        dotfiles_stow_manage: true

    - name: Setup nvim role (stable)
      ansible.builtin.import_role:
        name: nvim
      tags: [ nvim ]
      vars:
        nvim_bin_setup: true
        nvim_bin_version: "v0.11.4"

    - name: Setup nvim role (nightly)
      ansible.builtin.import_role:
        name: nvim
      tags: [ nvim ]
      vars:
        nvim_bin_setup: true
        nvim_bin_version: "nightly"

    - ansible.builtin.import_tasks: "tasks/nerdfonts.yml"
      tags: [ nerdfonts ]
      when: nerdfonts_setup | bool

    - ansible.builtin.import_tasks: "tasks/starship.yml"
      tags: [ starship ]

    - ansible.builtin.import_tasks: "tasks/ghostty.yml"
      tags: [ ghostty ]
