---
- hosts: localhost
  connection: local
  gather_facts: true

  ### VARS
  # vars of imported tasks
  vars:
    nerdfonts_setup: true
    nerdfonts_path: "/usr/local/share/fonts"
    nerdfonts_to_install:
      - NerdFontsSymbolsOnly
      - FiraCode
      - Overpass
      - JetBrainsMono
    conda_setup: true
    conda_url: "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-{{ ansible_architecture }}.sh"
    conda_path: "~/conda"


  ### PRE TASKS
  pre_tasks:
    - name: Update package cache
      tags: [ always ]
      become: true
      ansible.builtin.package: update_cache=yes
      changed_when: false


  ### TASKS
  tasks:
    - name: System bootstrap (repos and updates)
      tags: [ repos ]
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - "tasks/repos_{{ ansible_distribution }}.yml"
        - "tasks/repos_{{ ansible_os_family }}.yml"

    - ansible.builtin.import_tasks: "tasks/flatpak.yml"
      tags: [ flatpak, repos ]

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Setup git role
      ansible.builtin.import_role:
        name: git
      tags: [ git, vcs ]
      vars:
        git_manage_project_dirs: true
        git_project_dirs:
          - "~/Projects"

    - name: Setup conda role
      ansible.builtin.import_tasks: "tasks/conda.yml"
      tags: [ conda, dev ]
      when: conda_setup | bool

    - name: Manage dotfiles role
      ansible.builtin.import_role:
        name: dotfiles
      tags: [ dotfiles ]
      vars:
        dotfiles_github_repo: "git@github.com-personal:rflocfloc/dotfiles.git"
        dotfiles_github_ssh_key: "~/.ssh/id_ed25519_github.pub"
        dotfiles_delete_bashrc: true
        dotfiles_stow_manage: true

    - name: Setup nvim role (stable)
      ansible.builtin.import_role:
        name: nvim
      tags: [ nvim ]
      vars:
        nvim_bin_setup: true
        nvim_bin_version: "v0.11.4"

    - name: Setup nvim role (nightly)
      ansible.builtin.import_role:
        name: nvim
      tags: [ nvim ]
      vars:
        nvim_bin_setup: true
        nvim_bin_version: "nightly"

    - ansible.builtin.import_tasks: "tasks/nerdfonts.yml"
      tags: [ nerdfonts ]
      when: nerdfonts_setup | bool

    - ansible.builtin.import_tasks: "tasks/starship.yml"
      tags: [ starship ]

    # - ansible.builtin.import_tasks: "tasks/ghostty.yml"
    #   tags: [ ghostty ]

    - name: Install cli tools
      ansible.builtin.import_role:
        name: cli_tools
      tags: [ cli, software ]

    - name: Install flatpak apps
      tags: [ flatpak, software ]
      community.general.flatpak:
        state: present
        remote: flathub
        name: "{{ item }}"
      loop:
        - io.github.kolunmi.Bazaar
        - com.mattjakeman.ExtensionManager
        - com.github.tchx84.Flatseal
        - io.github.flattool.Warehouse
        - de.haeckerfelix.Fragments
        - it.mijorus.gearlever
        - io.github.vmkspv.netsleuth
        - net.nokyan.Resources
        - com.bitwarden.desktop
        - app.zen_browser.zen
        - org.inkscape.Inkscape
        - org.gimp.GIMP
        - md.obsidian.Obsidian
        - org.gnome.gitlab.somas.Apostrophe
        - org.telegram.desktop
        - com.bambulab.BambuStudio

    - name: Download AppImages
      tags: [ appimage, software ]
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: '755'
      loop_control:
        label: "Appimage at: {{ item.dest }}"
      loop:
        - url: "https://github.com/vial-kb/vial-gui/releases/download/v0.7.3/Vial-v0.7.3-x86_64.AppImage"
          dest: "~/Downloads/Vial-v0.7.3-x86_64.AppImage"
        - url: "https://github.com/FreeCAD/FreeCAD/releases/download/1.0.1/FreeCAD_1.0.1-conda-Linux-x86_64-py311.AppImage"
          dest: "~/Downloads/FreeCAD_1.0.1-conda-Linux-x86_64-py311.AppImage"
        - url: "https://github.com/pkgforge-dev/ghostty-appimage/releases/download/v1.1.3/Ghostty-1.1.3-x86_64.AppImage"
          dest: "~/Downloads/Ghostty-1.1.3-x86_64.AppImage"
