---
- hosts: localhost
  connection: local
  gather_facts: true

  # vars of imported tasks
  vars:
    nerdfonts_path: "/usr/local/share/fonts"
    nerdfonts_to_install:
      - NerdFontsSymbolsOnly
      - FiraCode
      - Overpass
      - JetBrainsMono

  pre_tasks:
    - name: Update package cache
      tags: [ always ]
      become: true
      ansible.builtin.package: update_cache=yes
      changed_when: false

    - name: System bootstrap (repos and updates)
      tags: [ repos ]
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - "tasks/repos_{{ ansible_distribution }}.yml"
        - "tasks/repos_{{ ansible_os_family }}.yml"

  roles:
    - role: git
      tags: [ git, vcs ]
      vars:
        git_manage_config: true
        git_user_name: "rflocfloc"
        git_user_email: "riccardoscandino@gmail.com"
        git_manage_project_dirs: true
        git_project_dirs:
          - "~/Projects"
          - "~/Projects/Personal"
          - "~/Projects/Work"

    - role: dotfiles
      tags: [ dotfiles ]
      vars:
        dotfiles_github_repo: "git@github.com-personal:rflocfloc/dotfiles.git"
        dotfiles_github_ssh_key: "~/.ssh/id_ed25519_github.pub"
        dotfiles_delete_bashrc: true
        dotfiles_stow_manage: true

    - role: nvim
      tags: [ nvim ]
      vars:
        nvim_bin_setup: true
        nvim_bin_version:
          - "v0.11.4"
          - "nightly"
        nvim_bin_dir_path: "/opt/nvim"
        nvim_bin_path: "/usr/local/bin/nvim"

  tasks:
    - ansible.builtin.import_tasks: "tasks/flatpak.yml"
      tags: [ flatpak, repos ]

    - ansible.builtin.import_tasks: "tasks/nerdfonts.yml"
      tags: [ nerdfonts ]

    - ansible.builtin.import_tasks: "tasks/starship.yml"
      tags: [ starship ]

    - ansible.builtin.import_tasks: "tasks/ghostty.yml"
      tags: [ ghostty ]
