---
- name: Install development tools by category
  hosts: dev_servers
  become: yes
  vars:
    # Define package categories
    core_dev_tools:
      - "{{ build_essentials }}"
      - make
      - gcc
      - git
      - curl
      - wget
      - unzip
      - zip

    modern_cli_tools:
      - "{{ fd_package }}"      # fd-find on Ubuntu, fd on Arch
      - fzf
      - "{{ ripgrep_package }}"  # ripgrep
      - "{{ bat_package }}"      # bat or batcat
      - tree
      - jq

    language_runtimes:
      - nodejs
      - npm
      - python3
      - "{{ python_pip }}"       # python3-pip or python-pip
      - "{{ python_venv }}"      # python3-venv

    dev_utilities:
      - vim
      - tmux
      - sqlite3
      - openssl

  tasks:
    - name: Install core development tools
      package:
        name: "{{ core_dev_tools }}"
        state: present
      tags: [core, dev]

    - name: Install modern CLI tools
      package:
        name: "{{ modern_cli_tools }}"
        state: present
      tags: [modern, cli, dev]

    - name: Install language runtimes
      package:
        name: "{{ language_runtimes }}"
        state: present
      tags: [languages, dev]

    - name: Install development utilities
      package:
        name: "{{ dev_utilities }}"
        state: present
      tags: [utilities, dev]

    # Special handling for distribution-specific packages
    - name: Install httpie (if available)
      package:
        name: httpie
        state: present
      ignore_errors: yes
      tags: [network, dev]
