---
- name: flatpak | Install Flatpak
  become: true
  ansible.builtin.package:
    name:
      - flatpak
    state: present

- name: flatpak | Install Flatpak plugin (Ubuntu)
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - gnome-software-plugin-flatpak
    state: present
  when: ansible_os_family == "Debian"

- name: flatpak | Add the FlatHub remote
  become: true
  community.general.flatpak_remote:
    name: "flathub"
    state: present
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
