---
- name: "nerdfonts: Ensure fonts directory exists"
  become: true
  ansible.builtin.file:
    path: "{{ nerdfonts_path }}"
    state: directory

- name: "nerdfonts: Install required packages"
  become: true
  ansible.builtin.package:
    name:
      - fontconfig
      - unzip
    state: present

- name: "nerdfonts: Download and extract Nerd Fonts"
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip"
    dest: "{{ nerdfonts_path }}"
    remote_src: true
  loop: "{{ nerdfonts_to_install }}"

- name: "nerdfonts: Update font cache"
  become: true
  ansible.builtin.command: "fc-cache -f"
