---
- name: "repos: Debian | Update packages"
  tags: [ repos ]
  become: true
  ansible.builtin.apt:
    name: "*"
    state: present
    update_cache: true

- name: "repos: Debian | APT autoremove"
  tags: [ repos ]
  become: true
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
