---
nvim_bin_setup: false
nvim_bin_version: "v0.11.4"
nvim_bin_dir_path: "/opt/nvim"
nvim_bin_path: "/usr/local/bin/nvim"

nvim_manage_config: false
nvim_dotfiles_github_repo: "https://github.com/rflocfloc/nvim-bootstrap.git"
nvim_dotfiles_github_ssh_key: ""
nvim_config_opts:
  - vim.opt.number = true
  - vim.opt.relativenumber = true
  - vim.opt.inccommand = 'split'
  - vim.opt.tabstop = 4
  - vim.opt.shiftwidth = 4
  - vim.opt.expandtab = true
  - vim.opt.smartcase = true
  - vim.opt.splitright = true
  - vim.opt.splitbelow = true
  - vim.opt.termguicolors = true
  - vim.opt.guicursor = ""
  - vim.opt.signcolumn = "yes"
  - vim.opt.swapfile = false
  - vim.opt.backup = false
  - vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
  - vim.opt.undofile = true
nvim_config_keymaps:
  - vim.keymap.set('n', '<Esc>', '<cmd>nohlsearch<CR>', {desc = "<Esc> to clear search highlights"})
  - vim.keymap.set('t', '<Esc>', '<C-\\><C-N>', {desc = "<Esc> to exit terminal mode"})
  - vim.keymap.set({'v', 'x'}, '<S-h>', '<gv', { noremap = true, silent = true, desc = 'Move selection to the left' })
  - vim.keymap.set({'v', 'x'}, '<S-l>', '>gv', { noremap = true, silent = true, desc = 'Move selection to the right' })
  - vim.keymap.set({'v', 'x'}, '<S-j>', ':m \'>+1<CR>gv=gv', { noremap = true, silent = true, desc = 'Move block selection down' })
  - vim.keymap.set({'v', 'x'}, '<S-k>', ':m \'<-2<CR>gv=gv', { noremap = true, silent = true, desc = 'Move block selection up' })
