- name: Load distribution-specific cli_utils variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/default.yml"

- name: Install core utils
  tags: cli_tools
  become: true
  ansible.builtin.package:
    name:
      - "{{ build_essentials }}"
      - curl
      - wget
      - "{{ dns_utils }}"
      - htop
      - lsof
      - lshw
      - ncdu
      - net-tools
      - "{{ nfs_client }}"
      - nmap
      - rsync
      - "{{ ssh }}"
      - sshfs
      - traceroute
      - mtr
      - whois
      - stow
    state: present

- name: Install productivity utils
  tags: cli_tools
  become: true
  ansible.builtin.package:
    name:
      - tree
      - screen
      - tmux
      - "{{ vim }}"
      - zoxide
      - fzf
    state: present
