---
- name: Ensure /opt/nvim directory exists
  become: true
  ansible.builtin.file:
    path: "{{ nvim_bin_dir_path }}"
    state: directory
    mode: '0755'

- name: Download and decompress nvim binary
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/download/{{ nvim_bin_version }}/nvim-linux-x86_64.tar.gz"
    dest: "/tmp/"
    remote_src: true

- name: Move nvim binary
  become: true
  ansible.builtin.copy:
    src: "/tmp/nvim-linux-x86_64/"
    dest: "{{ nvim_bin_dir_path }}/nvim-{{ nvim_bin_version }}/"
    remote_src: true
    mode: '0755'

- name: Ensure symlink nvim binary is not present
  become: true
  ansible.builtin.file:
    path: "{{ nvim_bin_path }}"
    state: absent

- name: Symlink nvim binary
  become: true
  ansible.builtin.file:
    src: "{{ nvim_bin_dir_path }}/nvim-{{ nvim_bin_version }}/bin/nvim"
    dest: "{{ nvim_bin_path }}"
    state: link
    force: true
