---
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family + '-' + ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Set admin packages list
  ansible.builtin.set_fact:
    cli_tools_admin_list: "{{ __cli_tools_admin_list | difference(cli_tools_excluded_packages) }}"
  when: cli_tools_admin_list is not defined

- name: Set dev packages list
  ansible.builtin.set_fact:
    cli_tools_dev_list: "{{ __cli_tools_dev_list | difference(cli_tools_excluded_packages) }}"
  when: cli_tools_dev_list is not defined
